version: "3.8"

services:
  app:
    container_name: app
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PORT}:${PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
